Казарцев ЛР 9
iDneprov/labs-first-course pull request #10
Opened 2022-10-26 19:01 UTC by ananasik558

![image](https://user-images.githubusercontent.com/114168943/198113571-ee44aa41-b1bc-4a1b-891e-1608f36c168c.png)
![image](https://user-images.githubusercontent.com/114168943/198113641-68c09a73-a6dd-4d31-bd8e-0366c32a7c78.png)

2022-10-26 19:13 UTC, ananasik558 reviewed
Вариант 9

2022-10-28 16:58 UTC, iDneprov requested changes
Пока не соответствует нашему стилю.
Неплохой пример применения нашего code style [девятая Лаба в исполнении Ирины](https://github.com/iDneprov/labs-first-course/pull/4/files).

2022-10-28 16:58 UTC, iDneprov commented on 1.c
> +int max(int a, int b) {
Все функции пишем в CamelCase с большой буквы

2022-10-28 16:58 UTC, iDneprov commented on 1.c
> +int Inext(int i, int j, int k, int l) {
Например, тут должно быть написано `INext`

2022-10-28 16:58 UTC, iDneprov commented on 1.c
> +    return (abs(max(i*(k+5),j*(k+6)))-abs(min(j*(k+7),l*(k+8)))) % 20;
Отделяй операторы от операнд проблемами

2022-10-28 16:58 UTC, iDneprov commented on 1.c
> +    return i>=5 && i<=10 && j<=-5 && j>=-10;
Вынеси константы в макросы

2022-10-28 16:58 UTC, iDneprov commented on 1.c
> +int in = 0;
Понятнее называй переменные

2022-10-28 16:58 UTC, iDneprov commented on 1.c
> +}
В конце файла должна быть пустая строка

2022-10-28 19:38 UTC, iDneprov requested changes
Пока не по кодстайлу, рекомендую глянуть [код Ирины](https://github.com/iDneprov/labs-first-course/pull/4/files). Только одностопные функции выноси в макросы.

2022-10-28 19:38 UTC, iDneprov commented on 1.c
> +int Max(int a, int b) {
Еще вынеси однострочники в мокросы, пожалуйста
Вот пример: `#define ABS(a) (a > 0) ? a : -a;`

2022-10-28 19:38 UTC, iDneprov commented on 1.c
> +    if( a < 0) {
Последний if избыточен

2022-10-28 19:38 UTC, iDneprov commented on 1.c
> +    return (abs (Max (i*(k+5),j*(k+6)))-abs (Min (j*(k+7),l*(k+8)))) % 20;
А где пробелы?

2022-10-28 19:38 UTC, iDneprov commented on 1.c
> +    return (abs (Max (i*(k+5),j*(k+6)))-abs (Min (j*(k+7),l*(k+8)))) % 20;
Я имел ввиду операторы, а не функции, ты не туда вставил

2022-10-28 19:38 UTC, iDneprov commented on 1.c
> +    return i % 10 + j % 10 + l % 10;
Вот тут норм

2022-10-28 19:38 UTC, iDneprov commented on 1.c
> +    return i>=5 && i<=10 && j<=-5 && j>=-10;
Так, блин

2022-10-28 19:38 UTC, iDneprov commented on 1.c
> +    return i>=5 && i<=10 && j<=-5 && j>=-10;
5, 10 — тоже константы

2022-10-28 19:38 UTC, iDneprov commented on 1.c
> +for( k = 0; k<=50; k++) {
Тут будет 51 итерация
И пробел после `(` лишний

2022-10-28 19:38 UTC, iDneprov commented on 1.c
> +    int I_NEW=INext(I, J, k, L);
переменный называем по camelCase со строчной

2022-10-28 19:38 UTC, iDneprov commented on 1.c
> +if(in) {
Блок под if перенеси в if на строке 52

2022-10-28 19:38 UTC, iDneprov commented on 1.c
> +
Одна пустая строка в конце файла, github скрывает первую, значит у тебя 2

2022-11-05 15:38 UTC, iDneprov commented
Все отлично)

2022-11-05 15:38 UTC, closed without merging