Евсеев ЛР№9
iDneprov/labs-first-course pull request #18
Opened 2022-10-28 19:05 UTC by yEvseev1

### **Евсеев Юрий**
**Лр № 9**
_Вариант 7_
### `Задание`

![5HFU_M5UcI8](https://user-images.githubusercontent.com/116905207/198712927-d2016709-f664-4ebe-b777-f6e1b8bd3799.jpg)
![5Qpam-KHE68](https://user-images.githubusercontent.com/116905207/198712946-901ce891-7212-479c-808e-6fdf7d4c8099.jpg)

### _В данной лр только вывод_

2022-10-28 19:51 UTC, iDneprov requested changes
Пока не по кодстайлу, рекомендую глянуть [код Ирины](https://github.com/iDneprov/labs-first-course/pull/4/files). Только одностопные функции выноси в макросы.

2022-10-28 19:51 UTC, iDneprov commented on main9.c
> +    return x*y < 0 ? x - ((x/y) - 1)*y : x - (x/y) * y;
Отделяй операторы пробелами от операнд

2022-10-28 19:51 UTC, iDneprov commented on main9.c
> +    return x > y ? x : y;
Однострочники лучше вынести в макрос, вот пример: `#define ABS(a) (a > 0) ? a : -a;`

2022-10-28 19:51 UTC, iDneprov commented on main9.c
> +int iNext(int i , int k, int l, int j){
Функции называем в CamelCase с заглавной

2022-10-28 19:51 UTC, iDneprov commented on main9.c
> +    if(((i >= 5) && (i <=15)) && ((j <= -5)&&(j >= -15))){
if лишний

2022-10-28 19:51 UTC, iDneprov commented on main9.c
> +    if(((i >= 5) && (i <=15)) && ((j <= -5)&&(j >= -15))){
И можно в макрос вынести

2022-10-28 19:51 UTC, iDneprov commented on main9.c
> +    int i = 11;
Константы задавай в define, вот пример: `#define I 11`

2022-10-28 19:51 UTC, iDneprov commented on main9.c
> +        int x = i;
называй переменные понятнее, iPrev, например

2022-10-28 19:51 UTC, iDneprov commented on main9.c
> +            i = iNext(x,y,z,k);
Но  лучше чтобы эти переменные назывались iNext

2022-10-28 19:51 UTC, iDneprov commented on main9.c
> +            i = iNext(x,y,z,k);
А функции с большой буквы

2022-10-28 19:51 UTC, iDneprov commented on main9.c
> +    int ans = PrevMain();
Странное название функции, лучше в main все занести в таком случае

2022-10-28 19:51 UTC, iDneprov commented on main9.c
> +    return 0;   // Если увеличить кол-во итерация, то точка попадает за  = 126
Склонения)

2022-10-28 19:51 UTC, iDneprov commented on main9.c
> +}
В конце файла должна быть пустая строка

2022-10-28 20:41 UTC, pegaster commented on main9.c
> +    return x*y < 0 ? x - ((x/y) - 1)*y : x - (x/y) * y;
Догадался, что mod и остаток от деления не одно и тоже — мое почтение

2022-10-29 07:42 UTC, iDneprov requested changes
Осталось немного замечаний, но в остальном отлично)

2022-10-29 07:42 UTC, iDneprov commented on main9.c
> +    if(((i >= 5) && (i <=15)) && ((j <= -5)&&(j >= -15))){
If так и не убрал(
Это логическое выражение, оно возвращает 0 и 1. А ты говоришь, что если 1, то нужно вернуть один, а в других случаях 0. Это бессмысленно.

2022-10-29 07:42 UTC, iDneprov commented on main9.c
> +    if(((i >= 5) && (i <=15)) && ((j <= -5)&&(j >= -15))){
И забыл пробел `-15))) {`

2022-10-29 07:42 UTC, iDneprov commented on main9.c
> +    int lPrev = L0;
После объявления переменных нужна пустая строка

2022-10-29 07:42 UTC, iDneprov commented on main9.c
> +    if (Checker(iPrev,jPrev)) {
Табуляция съехала, должно быть:
```
    for (int k = 0; k < 50; ++k) {
        if (Checker(iPrev,jPrev)) {
```
Все подвинь до строки 56
Если текстовый редактор норм, можно выделить текст и нажать на `tab`, а он все сделает за тебя

2022-11-05 15:51 UTC, iDneprov commented
Все исправил, моё почтение)

2022-11-05 15:51 UTC, closed without merging