Bespalov - ЛР9
iDneprov/labs-first-course pull request #19
Opened 2022-10-28 19:23 UTC by BespalovArtem

Добрый вечер!

2022-10-28 20:26 UTC, pegaster requested changes
Пока не по кодстайлу, рекомендую глянуть [код Ирины](https://github.com/iDneprov/labs-first-course/pull/4/files).

2022-10-28 20:26 UTC, pegaster commented on hello.c
> +    int i_center = 10;
Константы следует вынести в макросы
Пример: `#define I_CENTЕR 10`
Константы пишутся с большой буквы через нижние подчеркивания.
А переменные пишутся в camelCase со строчной буквы
Пример: `someVariable`

2022-10-28 20:26 UTC, pegaster commented on hello.c
> +    int place = (i_center - i)*(i_center - i) + (j_center - j)*(j_center - j);
Нужны пробелы между операторами и скобками

2022-10-28 20:26 UTC, pegaster commented on hello.c
> +    return place > 25 && place <= 100;
5 и 10 тоже следует вынести в макросы

2022-10-28 20:26 UTC, pegaster commented on hello.c
> +int check_in_area(int i, int j){
Во-первых функции мы пишем в CamelCase с заглавной буквы, а во-вторых перед фигурной скобкой нужен пробел
Пример: `CheckInArea(int i, int j) {`

2022-10-28 20:26 UTC, pegaster commented on hello.c
> +}
Отделяй функции при описании пустыми строками

2022-10-28 20:26 UTC, pegaster commented on hello.c
> +    for(int k=0; k<=50; ++k){
цикл `for` по кодстайлу пишется так: `for (int k = 0; k <= 50; ++k) {`
и между операндами и операторами нужны пробелы

2022-10-28 20:26 UTC, pegaster commented on hello.c
> +    printf("i = %d; j = %d; l = %d", i, j, l);
Добавь `\n`, как в 48 строке

2022-10-28 20:26 UTC, pegaster commented on hello.c
> +        if(check_in_area(i, j)){
`if (check_in_area(i, j)) {`

2022-10-28 20:26 UTC, pegaster commented on hello.c
> +int main (void) {
`main(void)`

2022-10-28 20:26 UTC, pegaster commented on hello.c
> +    laba9(i, j, l);
Вынес зря, лучше в main вставь код из этой функции

2022-10-29 11:45 UTC, BespalovArtem commented
****ЛР №9**
Беспалов Артем 

Задание
Вариант №5**
![image](https://user-images.githubusercontent.com/75415627/198829592-3a81652d-106c-4e78-b110-608696a957bd.png)

2022-11-05 15:54 UTC, iDneprov requested changes
Код еще не соответствует кодстайлу, поправь, пожалуйста, до следующего занятия

2022-11-05 15:54 UTC, iDneprov commented on lab9
> +
Лишняя пустая срока

2022-11-05 15:54 UTC, iDneprov commented on lab9
> +int Lnext(int i, int j, int k, int l) {
`Lnext` не по кодстайлу, должно быть `LNext`
Каждое слово с новой строки

2022-11-10 20:51 UTC, pegaster requested changes
Сделать у файла расширение `.c` и исправить косяки

2022-11-10 20:51 UTC, pegaster commented on lab9
> +    return num2;
Используй тернарный оператор

2022-11-10 20:51 UTC, pegaster commented on lab9
> +    return -1 * num;
Используй тернарный оператор

2022-11-10 20:51 UTC, pegaster commented on lab9
> +    return -1 * num;
`-num`

2022-11-10 20:51 UTC, pegaster commented on lab9
> +#define I -1
Лучше написать `I_START` или `I_0` потому что это не переменная, а замена кусков в коде и она может заменить то, что ты не хочешь, поэтому название должно быть таким, которое точно не окажется частью названия функции или переменной

2022-11-10 20:51 UTC, pegaster commented on lab9
> +        l = LNext(l, i, j, l);
Ты в формулы для `j` и `l` подставишь значения `i` для следующего шага, что неверно

2022-11-27 10:39 UTC, closed without merging