Kazartsev-lab11
iDneprov/labs-first-course pull request #40
Opened 2022-11-09 13:00 UTC by ananasik558

Вариант 23
![12](https://user-images.githubusercontent.com/114168943/200837011-824aaf6b-b983-4035-80ac-b38de5c7205f.jpg)

2022-11-09 18:08 UTC, pegaster requested changes
Предпринял попытку обмануть систему, но попытка не самая удачная.
Во-первых из-за того, что `k` не инициализировано, там левое число будет. Но даже если исправить этот косяк, на тестах работает некорректо, на тесте `100000000005 ` выдает 1, хотя это число больше, чем 2 в 36 степени и в 16 бит явно не влезет. А еще на тесте `5` выдает 0, из-за того, что нет в конце пробела или переноса строки
Пока работа к сдаче не допускается

2022-11-09 18:50 UTC, iDneprov commented
Денис, я же говорил, что для считывания в 11, 12 рабах можно использовать только `getchar()`

2022-11-11 07:23 UTC, pegaster requested changes
Есть замечания по кодстайлу, плюс мне не нравится, что у тебя такие вложеные циклы, я апрувну с ними, после исправления остальных косяков, но на 5 при сдаче можешь не расчитывать

2022-11-11 07:23 UTC, pegaster commented on main.c
> +        if( elem != ' ') {
`if (elem != ' ') {`

2022-11-11 07:23 UTC, pegaster commented on main.c
> +    while(1) {
`while (1) {`

2022-11-11 07:23 UTC, pegaster commented on main.c
> +                if(number <= 32767) {
Самое большое 16 битное число это `65535` потому что можно беззнаковые брать

2022-11-11 11:49 UTC, pegaster approved these changes
Работа допускается к сдаче

2022-11-19 11:21 UTC, closed without merging